# Generated by Django 4.2.6 on 2024-01-18 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Apply_job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")],
                        default="Male",
                        max_length=20,
                    ),
                ),
                ("experience", models.FloatField(default=0.0)),
                ("resume", models.FileField(default="", upload_to="")),
                ("coverletter", models.CharField(max_length=200)),
                ("company_name", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("phone", models.CharField(default="", max_length=40)),
                ("email", models.EmailField(default="", max_length=60)),
                ("subject", models.TextField(max_length=200)),
                ("desc", models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="Post_job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("company_name", models.CharField(max_length=200)),
                (
                    "employment_status",
                    models.CharField(
                        choices=[
                            ("Part Time", "Part Time"),
                            ("Full Time", "Full Time"),
                            ("Freelance", "Freelance"),
                        ],
                        max_length=20,
                    ),
                ),
                ("vacancy", models.CharField(max_length=10, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Others", "Others"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("details", models.TextField()),
                ("responsibilities", models.TextField()),
                ("experience", models.CharField(max_length=100)),
                ("other_benefits", models.CharField(max_length=100)),
                ("job_location", models.CharField(max_length=100)),
                ("salary", models.CharField(blank=True, max_length=20, null=True)),
                ("application_deadline", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
