# Generated by Django 4.2.6 on 2024-01-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_site", "0002_post_job_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post_job",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="my_site/images"),
        ),
    ]
