# Generated by Django 4.2.6 on 2024-01-21 12:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("my_site", "0003_alter_post_job_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post_job",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
