# Generated by Django 4.2.6 on 2024-01-21 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("my_site", "0004_post_job_timestamp"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post_job",
            old_name="timestamp",
            new_name="datepost",
        ),
    ]
