# Generated by Django 4.2.6 on 2024-03-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_site", "0007_alter_apply_job_resume_alter_post_job_datepost"),
    ]

    operations = [
        migrations.AddField(
            model_name="apply_job",
            name="github",
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name="apply_job",
            name="linkedin",
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name="apply_job",
            name="resume",
            field=models.FileField(default="", upload_to=""),
        ),
    ]
